Add debug login
Signed-off-by: Caio Pereira <caio.pereira@foundries.io>

diff --git a/.github/workflows/fio-app-ci.yml b/.github/workflows/fio-app-ci.yml
--- a/.github/workflows/fio-app-ci.yml
+++ b/.github/workflows/fio-app-ci.yml
@@ -49,6 +49,15 @@ jobs:
           username: "doesntmatter"
           password: ${{ secrets.FIO_TOKEN  }}
       -
+        name: Verify Login
+        run: |
+              if ! docker info; then
+                echo "Docker login failed";
+                exit 1;
+              else
+                echo "Docker login succeeded!";
+              fi
+      -
         name: Build and push docker image
         id: docker_build
         uses: docker/build-push-action@v3
